### ISSUE TITLE
with the new socker, getting a SIGSEGV

### ISSUE THREAD

**Issue by aruniiird** [cosiner/socker#1]
Getting a following output, while running a simple socker program, which connects to a host and try to run 'pwd' command...

Output
---------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11b475a]

goroutine 1 [running]:
vendor/github.com/cosiner/socker.FsSftp.IsNotExist(0xc4200ea060, 0x0, 0x0, 0x0, 0x0, 0x1317340)
        /Users/arun/aruns/programming/go/sockerTest/src/vendor/github.com/cosiner/socker/fs_sftp.go:83 +0x4a
vendor/github.com/cosiner/socker.NewFsSftp(0xc4200ea060, 0xc4200da090, 0x0)
        /Users/arun/aruns/programming/go/sockerTest/src/vendor/github.com/cosiner/socker/fs_sftp.go:26 +0x1d6
vendor/github.com/cosiner/socker.NewSSH(0xc4200a0080, 0x0, 0x0, 0xb, 0xc420096000, 0xc4200a0080)
        /Users/arun/aruns/programming/go/sockerTest/src/vendor/github.com/cosiner/socker/ssh.go:141 +0xc1
vendor/github.com/cosiner/socker.Dial(0x122e158, 0xb, 0xc420049f20, 0x0, 0x0, 0x0, 0xc420049ea8, 0xfd0000000100fa42, 0x8)
        /Users/arun/aruns/programming/go/sockerTest/src/vendor/github.com/cosiner/socker/ssh.go:165 +0xd7
main.main()
        /Users/arun/aruns/programming/go/sockerTest/src/sockerTest/sockerTest.go:11 +0xe3

**Comment by aruniiird** [comment]
Tried with an older version of socker and it is working fine...

**Comment by zhuah** [comment]
@aruniiird Thanks for this reporting, i have fixes it in the latest commit.

**Comment by aruniiird** [comment]
Thanks @cosiner , the new fix is working fine (=
