### ISSUE TITLE
panic with latest "golang.org/x/crypto/ssh"

### ISSUE THREAD

**Issue by snowcrumble** [cosiner/socker#2]
when i update ssh "go get -u golang.org/x/crypto/ssh"
then my exe panic like this:

panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd76f6]

goroutine 1 [running]:
panic(0x22ca60, 0xc4200100b0)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cosiner/socker.(*SSH).Close(0x0)
	/Users/Snow/gowork/src/github.com/cosiner/socker/ssh.go:221 +0x26
panic(0x22ca60, 0xc4200100b0)
	/usr/local/Cellar/go/1.7.4_1/libexec/src/runtime/panic.go:458 +0x243
main.platformUninstall(0xc420084ca0, 0xe, 0xc420084caf, 0x5, 0xc420078a38, 0x7, 0x0)

I modified "cosiner/socker/ssh.go" line 61 with:
 `config := &ssh.ClientConfig{HostKeyCallback: ssh.InsecureIgnoreHostKey()}`
then no panic.

**Comment by zhuah** [comment]
@SnowCrumble Thanks for reporting, this has been fixed.
